admin_api_controllers:
    resource: ../../src/UI/AdminAPI/Controller
    type: annotation
    prefix: admin/api/

public_api_controllers:
    resource: ../../src/UI/PublicAPI/Controller
    type: annotation
    prefix: public/api/

kernel:
    resource: ../../src/Kernel.php
    type: annotation